### ISSUE TITLE
"Index update failed for 1 devices"

### ISSUE THREAD

**Issue by skerit** [syncthing/syncthing-lite#12] opened 2018-01-13 16:20 UTC
As soon as I've added my device I get the `Index update failed for 1 devices` notification, and unfortunately nothing else.

When I close the device and open it again I'm left in the dark as to what's happening, and pressing on the device in the "Devices" tab does nothing.

Clicking on "Update remote index" just gives the `Index update failed for 1 devices` notification agian.

The syncthing running on the desktop is v0.14.43, by the way.

**Comment by lapo-luchini** [comment] 2018-01-15 10:48
It happens to me too, but then I force-close, re-open the app… and the content seems to be there.
(but when I try to update, it fails again; and if I try to open any file, it crashes)

**Comment by skerit** [comment] 2018-01-15 10:59
@lapo-luchini Interesting, I'm never able to see any files, no matter how many times I close and re-open it. ("No folder available" in the "Folders" tab)

The icon of the device I've added is green though, so I guess it is able to create a connection.

**Comment by Pazuu** [comment] 2018-01-17 20:18
This is working for me now with version 1.3 🐙 :)

**Comment by skerit** [comment] 2018-01-17 21:17
I removed the device and added it again in version 1.3, but I'm still getting the same error.

**Comment by Nutomic** [comment] 2018-01-18 04:37
@skerit Are you running syncthing-android at the same time? And can you post logs?

**Comment by skerit** [comment] 2018-01-19 17:46
I've noticed that when I start the index refresh in `syncthing-lite`, the server will throw these tls-related errors:

```
[3CZLW] 18:42 INFO: Listen (BEP/tcp): TLS handshake: remote error: tls: illegal parameter
[3CZLW] 18:42 INFO: Listen (BEP/relay): TLS handshake: remote error: tls: illegal parameter
```

**Comment by ImPat** [comment] 2018-01-22 07:00
@skerit Related to issue #6

**Comment by Nutomic** [comment] 2018-01-24 08:59
There was a problem where Android does not support TLS 1.1/1.2 connections by default. This should be fixed in https://github.com/Nutomic/syncthing-java/commit/9807cd1ad3fe0aa1d5b266be7aa7674f6c909b01. But there are still more bugs in the code...

**Comment by ImPat** [comment] 2018-01-24 21:57
This is great news! That would explain why it only works on some android devices and not on others.

**Comment by TaoK** [comment] 2018-01-25 12:56
I just installed today, and have the same symptoms as @skerit - no index update at all, no folders. If I understand @Nutomic's comment correctly, there is a fix not on Play Store yet, so build from source might fix it (or wait for next publish to store)...?

**Comment by Nutomic** [comment] 2018-01-25 18:45
Correct @TaoK. I will make a new release soon, after I finish what I'm currently working on.

**Comment by ImPat** [comment] 2018-01-26 07:36
[I've compiled an APK with the updated syncthing-java. ](https://drive.google.com/open?id=1IMwfJ35TOG6s_FW_6xs64dtJZnfqoO5a). [Virustotal Link :)](https://www.virustotal.com/#/file/e1722550991b624a10548c88772462025c1ddf3887d5a969f149d5da9622b3d9/detection)

**Comment by ImPat** [comment] 2018-01-26 22:18
Nope. Can't get it to work even with the new APK. Still get a TLS error. I'm probably just stupid and it somehow compiled after gradle install without actually using the updated synching-java.

**Comment by skerit** [comment] 2018-01-27 14:49
@Nutomic @ImPat: I just installed @Nutomic's new version 0.1.4, but it still won't work I'm afraid. The server log still shows the same handshake error. (And yeah, I cleared the android application cache and all)

**Comment by Nutomic** [comment] 2018-01-27 15:33
@skerit Can you post a logcat from the Android side with that error?

**Comment by skerit** [comment] 2018-01-27 16:08
Sure, here you go: (I just obfuscated the addresses a bit)

[syncthing-logcat.log](https://github.com/Nutomic/syncthing-lite/files/1670221/syncthing-logcat.log)

**Comment by Nutomic** [comment] 2018-01-27 17:22
@skerit And what Android version are you using?

**Comment by skerit** [comment] 2018-01-27 18:05
Android 7.0 running on a Galaxy S8. Kernel 4.4.13

**Comment by Nutomic** [comment] 2018-01-27 18:14
Hmm this is weird, @lapo-luchini had a similar issue with Android 7 (which seems to be fixed now). However, the only info I can find is for Android 5.0 and lower, and I can't reproduce this on my Android 7.1 device either.

**Comment by ImPat** [comment] 2018-01-28 18:34
I still have the same error. Maybe a TouchWiz related issue?

**Comment by ImPat** [comment] 2018-02-03 17:18
> I still have the same error. Maybe a TouchWiz related issue?
Yep. Got it working on LOS 14.1 (7.1.2) :) Doesn't work on any TouchWiz device I have though.

**Comment by skerit** [comment] 2018-02-08 10:52
So I tried version 0.2.0: adding a new device is reported as successful, the icon turns green immediately, but no folders ever show up. I don't get the "index update failed" popup anymore, though. I'd have to take a look at the logcat again, but I guess nothing's changed there.

**Comment by Nutomic** [comment] 2018-02-08 14:11
Can you make sure that Syncthing on the other device does not show Syncthing Lite as connected before you start the app? Were you doing anything (eg upload or download files) when this happened?

**Comment by mrbar42** [comment] 2018-02-10 20:22
After i added a device and restarted the app, the shared folders show up with 0 file 0 directories and on computer syncthing webGUI i get prompted to add all of the shared folders with name as id, so i think this might be it

**Comment by skerit** [comment] 2018-03-22 18:07
Well some good news: my S8 finally upgraded to Oreo and Syncthing-lite started working immediately.

**Comment by l-jonas** [comment] 2018-12-09 11:32
It is very likely that this issue does not occur anymore. Due to that, I'm closing it now. If it still occurs, please create a new issue.

**Closed by l-jonas** 2018-12-09 11:32 UTC
Labels: Type: Bug
