### ISSUE TITLE
Back arrow behaviour

### ISSUE THREAD

**Issue by Newar417** [syncthing/syncthing-lite#130] opened 2018-12-13 03:01 UTC
0.3.8

Browsing through the folders, let's say:

Sync -> Documents -> Year 2017 -> July

From there, the back arrow in the upper left takes me back to the general shared folder overview. However, I would expect it to take me back to "Year 2017". Maybe have two arrows, one pointing backwards to go to "root" and one pointing up that takes you back one level higher? Similar to a file explorer.

**Comment by l-jonas** [comment] 2018-12-13 06:37
Which file explorer? Can you add a screenshot?

**Comment by Newar417** [comment] 2018-12-13 16:13
Some examples, generally look in the upper left area.

pcmanfm:
https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/I/m/PCManFM_file_manager_0.9.3.png

nemo: https://2.bp.blogspot.com/-9mk8C97aGyE/Vht1KrG61CI/AAAAAAAAElU/5ZUQkQRMV3k/s320/3.jpg

konqueror:
https://konqueror.org/pics/konqueror-network-transparency.png

Windows: https://images.techhive.com/images/article/2015/09/fileexplorer-100612583-large.jpg

**Comment by l-jonas** [comment] 2018-12-13 18:13
Why didn't you say that you are talking about desktop file managers? The problem is that it should fit in Android and 2 buttons in the upper left look strange. However, I could think of a home icon at the upper right (to go to the folder list) and using the up-button (in the upper left) to go one level back.

**Comment by l-jonas** [comment] 2018-12-13 18:47
Please take a look at https://github.com/syncthing/syncthing-lite/pull/135

**Comment by l-jonas** [comment] 2019-01-01 07:49
#135 was merged so I'm closing this for now

**Closed by l-jonas** 2019-01-01 07:49 UTC
