### ISSUE TITLE
cannot upload files

### ISSUE THREAD

**Issue by Pazuu** [syncthing/syncthing-lite#108] opened 2018-12-03 21:35 UTC
With version 0.3.7 i cannot upload files. The app stays in the uploadong process view forever. 

Thanks again!! :smiley_cat:

**Comment by l-jonas** [comment] 2018-12-04 06:06
@Pazuu Please use the search next time (or look at the issue list). This is a duplicate of <https://github.com/syncthing/syncthing-lite/issues/70>.

**Closed by l-jonas** 2018-12-04 06:06 UTC
